### ISSUE TITLE
librarians.yml not being loaded properly

### ISSUE THREAD

**Issue by alfalfascout** [alfalfascout/CustomVillageTrades#1]
I suspect librarians.yml isn't being loaded properly in [createFiles()](https://github.com/alfalfascout/CustomVillageTrades/blob/e1ea735ae352d4f798a514ca15cbc980760ecec3/src/main/java/com/alfalfascout/CustomVillageTrades/CustomVillageTrades.java#L62-L96), because I can't access it at all afterwards. Meanwhile, config.yml seems to load just fine?

NullPointerException on this line: https://github.com/alfalfascout/CustomVillageTrades/blob/e1ea735ae352d4f798a514ca15cbc980760ecec3/src/main/java/com/alfalfascout/CustomVillageTrades/CustomVillageTrades.java#L33

Stack Trace:

```
[01:28:39 ERROR]: Error occurred while enabling CustomVillageTrades v0.1 (Is it up to date?)
java.lang.NullPointerException
    at com.alfalfascout.CustomVillageTrades.CustomVillageTrades.onEnable(CustomVillageTrades.java:33) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.jar:git-Spigot-c55900f-9856d8a]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]
    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]
    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]
    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot-1.10.jar:git-Spigot-c55900f-9856d8a]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by alfalfascout** [comment]
The new [createFiles()](https://github.com/alfalfascout/CustomVillageTrades/blob/b3de30bf9e1f9f801ebb23fe2185b09182a29d6a/src/main/java/com/alfalfascout/CustomVillageTrades/CustomVillageTrades.java#L51-L55) seems to have fixed this.
